version: "3"

services:
  # https://zincsearch-docs.zinc.dev/installation/
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    environment:
      - TZ=Europe/Vienna
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=admin
    volumes:
      - ./data/zinc:/data
    ports:
      - 4080:4080
    networks:
      - web
      - elastic
    labels:
      - traefik.enable=false
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # https://zincsearch-docs.zinc.dev/ingestion/fluent-bit/
  fluent-bit:
    image: fluent/fluent-bit:1.9
    container_name: fluent-bit
    command:
      - /fluent-bit/bin/fluent-bit
      - --config=/etc/fluent-bit/fluent-bit.conf
    environment:
      - TZ=Europe/Vienna
      - FLB_ES_HOST=zinc
      - FLB_ES_PORT=4080
      - FLB_ES_USER=admin
      - FLB_ES_PASSWORD=admin
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    volumes:
      - ./conf/:/etc/fluent-bit/:ro
    networks:
      - elastic
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # https://github.com/nefarius/Mana
  mana:
    image: nefarius.azurecr.io/mana:latest
    container_name: mana
    restart: always
    ports:
      - 5601:80
    environment:
      - TZ=Europe/Vienna
      - Mana__Elastic__ServerUrl=http://zinc:4080/
      - Mana__Elastic__Username=admin
      - Mana__Elastic__Password=admin
    networks:
      - web
      - elastic
    labels:
      # assumes we sit behind Traefik proxy
      - traefik.enable=true
      - traefik.http.routers.mana-ui.rule=Host(`logs.example.org`)
      - traefik.http.routers.mana-ui.entrypoints=web-secure
      - traefik.http.routers.mana-ui.tls=true
      - traefik.http.routers.mana-ui.tls.certresolver=le
      - traefik.http.services.mana-ui.loadbalancer.server.port=80
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  elastic:
  web:
    external: true