version: "3"

services:
  # https://docs.zincsearch.com/quickstart/#installation
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    container_name: zinc
    restart: always
    environment:
      - ZINC_DATA_PATH=/data
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=admin
    volumes:
      - ./data/zinc:/data
    ports:
      - 4080:4080
    networks:
      - web
      - elastic
    labels:
      - traefik.enable=false
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # https://docs.zincsearch.com/ingestion/fluent-bit/
  fluent-bit:
    image: fluent/fluent-bit:1.8
    container_name: fluent-bit
    command:
      - /fluent-bit/bin/fluent-bit
      - --config=/etc/fluent-bit/fluent-bit.conf
    environment:
      - FLB_ES_HOST=zinc
      - FLB_ES_PORT=4080
      - FLB_ES_USER=admin
      - FLB_ES_PASSWORD=admin
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    volumes:
      - ./conf/:/etc/fluent-bit/:ro
    networks:
      - elastic
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # TODO: replace
  kibana:
    image: yashlogic/amazon-opendistro-for-elasticsearch-kibana-logtrail:1.3.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - ELASTICSEARCH_URL=http://zinc:4080/es
      - ELASTICSEARCH_HOSTS=http://zinc:4080/es
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    networks:
      - web
      - elastic
    labels:
      - traefik.enable=true
      - traefik.http.routers.kibana.rule=Host(`logs.example.org`) && PathPrefix(`/kibana`)
      - traefik.http.routers.kibana.entrypoints=web-secure
      - traefik.http.routers.kibana.tls=true
      - traefik.http.routers.kibana.tls.certresolver=le
      - traefik.http.services.kibana.loadbalancer.server.port=5601
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  elastic:
  web:
    external: true